caronas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from comum.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('comum.urls', namespace="comum")),
    url(r'^$', index, name="index")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comum/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^inicio/', views.index, name='index'),
    url(r'^estatistica/', views.estatistica, name='estatistica'),
    url(r'^login/', views.login_aplicacao, name='login'),
    url(r'^logout/', views.logout_aplicacao, name='logout'),
    url(r'^novo_depoimento/', views.novo_depoimento, name='novo_depoimento'),
    url(r'^apagar_depoimento/(?P<id>\d+)/$', views.apagar_depoimento, name='apagar_depoimento'),
    url(r'^novo_comentario/(?P<id>\d+)/$', views.novo_comentario, name='novo_comentario'),
    url(r'^nova_mensagem/(?P<id>\d+)/$', views.nova_mensagem, name='nova_mensagem'),
    url(r'^mensagens/$', views.ver_mensagens, name='mensagens'),
    url(r'^mensagens/(?P<id>\d+)/$', views.mensagens, name='mensagens'),
    url(r'^tipos_depoimento/$', views.tipos_depoimento, name='tipos_depoimento'),
    url(r'^tipos_depoimento/novo/$', views.novo_tipo_depoimento, name='novo_tipo_depoimento'),
    url(r'^novo_usuario/$', views.novo_usuario, name='novo_usuario'),
    url(r'^nova_rota/$', views.nova_rota, name='nova_rota'),
    url(r'^novo_ponto/$', views.novo_ponto, name='novo_ponto'),
    url(r'^novo_pedido_carona/$', views.novo_pedido_carona, name='novo_pedido_carona'),
    url(r'^novo_oferecer_carona/$', views.novo_oferecer_carona, name='novo_oferecer_carona'),
    url(r'^historico/$', views.historico, name='historico'),

]

comum/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Usuario(User):
    telefone = models.CharField(max_length=11)
    nome = models.CharField(max_length=100)
    cidade = models.CharField(max_length=35)


class PontosDeInteresse(models.Model):
    localizacao = models.CharField(max_length=250)
    horario = models.TimeField()
    usuario = models.ManyToManyField(Usuario)


class RotasDeInteresse(models.Model):
    localizacao_atual = models.CharField(max_length=250)
    localizacao_final = models.CharField(max_length=250)
    horario = models.TimeField()
    usuario = models.ManyToManyField(Usuario)
    

class Veiculo(models.Model):
    placa = models.CharField(max_length=7)
    cor = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    ano = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2020)])
    

class Motorista(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    cnh = models.CharField(max_length=11)
    veiculo = models.OneToOneField(Veiculo, on_delete=models.CASCADE)


class Carona(models.Model):
    ponto_embarque = models.CharField(max_length=250)
    motorista = models.ForeignKey(Motorista, on_delete=models.CASCADE, null=True, blank=True)
    destino = models.CharField(max_length=250)
    data = models.DateField()


class Passageiro(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    carona = models.ManyToManyField(Carona)


class Avaliacao(models.Model):
    nota = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    motorista = models.ManyToManyField(Motorista)
    passageiro = models.ManyToManyField(Passageiro)
    

class Comentario(models.Model):
    titulo = models.CharField(max_length=15)
    texto = models.TextField()
    avaliacao = models.ForeignKey(Avaliacao, on_delete=models.CASCADE)


# Create your models here.
class TipoDepoimentos(models.Model):
    nome = models.CharField(max_length=30)
    def __unicode__(self):
        return '%s' % (self.nome)
    def __str__(self):
        return '%s' % (self.nome)

class Depoimentos(models.Model):
    titulo = models.CharField(max_length=100)
    conteudo = models.TextField()
    autor = models.ForeignKey(User)
    tipo = models.ForeignKey(TipoDepoimentos, null=True)
    document = models.FileField(upload_to='documents/', null=True, blank=True)

class Comentario(models.Model):
    conteudo = models.CharField(max_length=500)
    autor = models.ForeignKey(User)
    pai = models.ForeignKey(Depoimentos, related_name="comentarios")

class Mensagem(models.Model):
    conteudo = models.CharField(max_length=500)
    autor = models.ForeignKey(User, related_name="mensagens")
    destinatario = models.ForeignKey(User, related_name="destinos")
    lida = models.BooleanField(default=False)

comum/forms.py
# -*- coding: utf-8 -*-
from django import forms
from comum.models import *
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class NovoDepoimentoForm(forms.ModelForm):
    endereco = forms.CharField(label=_("Endereco"))
    class Meta:
        model = Depoimentos
        fields = ('titulo', 'conteudo', 'tipo', 'document')
        labels = {
            'titulo': u"Título",
            'conteudo': u"Conteúdo",
            'tipo': u"Tipo",
            'document':"Anexe uma imagem",
        }

class NovaRotaForm(forms.ModelForm):
    horario = forms.DateTimeField(widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M',
                                                           attrs={'class': 'form-control'}),
                                    input_formats=('%d/%m/%Y %H:%M',), label="Dia/Hora", required=True)
    class Meta:
        model = RotasDeInteresse
        fields = ('localizacao_atual', 'localizacao_final', 'horario')
        labels = {
            'localizacao_atual': u"De",
            'localizacao_final': u"Até",
            'horario': u"Dia/Hora",
        }

class NovoPontoForm(forms.ModelForm):
    horario = forms.TimeField(widget=forms.TimeInput(format='%H:%M',
                                                           attrs={'class': 'form-control'}),
                                    input_formats=('%H:%M',), label="Dia/Hora", required=True)
    class Meta:
        model = PontosDeInteresse
        fields = ('localizacao', 'horario')
        labels = {
            'localizacao': u"Local",
            'horario': u"Horário",
        }


class CaronaForm(forms.ModelForm):
    data = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y',
                                                           attrs={'class': 'form-control'}),
                                    input_formats=('%d/%m/%Y',), label="Data", required=True)
    ponto_embarque = forms.ChoiceField(choices=[(None, "------")], label="Ponto de Embarque",
                                              widget=forms.Select(attrs={"class": "form-control"}))
    class Meta:
        model = Carona
        fields = ('data', 'destino', 'ponto_embarque')
        labels = {
            'destino': u"Destino",
            "data": "Data"
        }

    def __init__(self, usuario, *args, **kwargs):
        super(CaronaForm, self).__init__(*args, **kwargs)
        rotas_qs = RotasDeInteresse.objects.filter(usuario=usuario)
        pontos_qs = PontosDeInteresse.objects.filter(usuario=usuario)
        rotas = [u"Às %s em %s até %s"
            %(str(r.horario), r.localizacao_atual.split(',')[0], r.localizacao_final.split(',')[0]) for r in rotas_qs]
        pontos = [u"Às %s em %s"%(str(p.horario), p.localizacao.split(',')[0]) for p in pontos_qs]
        dictionary = dict(zip(pontos + rotas, pontos + rotas))
        lista = [(k, v) for k, v in dictionary.items()] 

        self.fields['ponto_embarque'].choices = lista

class TipoUsuarioForm(forms.Form):
    tipo = forms.ChoiceField(choices=[(1,'Passageiro'), (2, 'Motorista')], required=True, widget=forms.RadioSelect)

class NovoTipoDepoimentoForm(forms.ModelForm):
    class Meta:
        model = TipoDepoimentos
        fields = ('nome',)
        labels = {
            'nome': u"Nome",
        }

class NovoUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        labels = {
            'username': u"Usuário",
            'password': "Senha"
        }

class NovoUserForm(forms.ModelForm):
    # error_messages = {
    #     'password_mismatch': _("As duas senhas não são iguais"),
    # }

    email = forms.CharField(label=_("Email do Usuário"), required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label=_("Senha"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label=_("Confirmação de senha"),
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                help_text=_("Enter the same password as above, for verification."))
    cidade = forms.CharField(label=_("Cidade"), required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    telefone = forms.CharField(label=_("Telefone"), required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo = forms.MultipleChoiceField(choices=[(1,'Quero Solicitar uma Carona'), (2, 'Quero Oferecer uma Carona')], required=True, widget=forms.CheckboxSelectMultiple)
    cnh = forms.IntegerField(label=_("CNH"), min_value=0, required=False)
    placa_veiculo = forms.CharField(label=_("Placa do Veículo"), required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    cor_veiculo = forms.CharField(label=_("Cor do Veículo"), required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    ano_veiculo = forms.IntegerField(label=_("Ano do Veículo"), min_value=0, required=False)
    modelo_veiculo = forms.CharField(label=_("Veículo"), required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ("username",)
        widgets = {
            "username": forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                "As duas senhas precisam ser iguais"
            )
        return password2

    def clean(self):
        tipo = self.cleaned_data.get("tipo", None)
        cnh = self.cleaned_data.get("cnh", None)
        placa_veiculo = self.cleaned_data.get("placa_veiculo", None)
        cor_veiculo = self.cleaned_data.get("cor_veiculo", None)
        ano_veiculo = self.cleaned_data.get("ano_veiculo", None)
        modelo_veiculo = self.cleaned_data.get("modelo_veiculo", None)
        if not tipo:
            raise forms.ValidationError(
                "Você precisa selecionar se deseja ser Passageiro ou Motorista"
            )

        if '2' in tipo:
            if not (cnh and placa_veiculo and cor_veiculo and ano_veiculo and modelo_veiculo):
                raise forms.ValidationError(
                    u"Preencha todas as informações sobre o Motorista"
                )

        return self.cleaned_data

    def save(self, commit=True):
        cnh = self.cleaned_data.get("cnh", None)
        placa_veiculo = self.cleaned_data.get("placa_veiculo", None)
        cor_veiculo = self.cleaned_data.get("cor_veiculo", None)
        ano_veiculo = self.cleaned_data.get("ano_veiculo", None)
        modelo_veiculo = self.cleaned_data.get("modelo_veiculo", None)
        cidade = self.cleaned_data.get("cidade", None)
        telefone = self.cleaned_data.get("telefone", None)
        tipo = self.cleaned_data.get("tipo", None)

        # user = super(NovoUserForm, self).save(commit=False)
        usuario = Usuario()
        motorista = Motorista()
        passageiro = Passageiro()
        usuario.set_password(self.cleaned_data["password1"])
        usuario.username = self.cleaned_data.get("username", None)
        usuario.email=self.cleaned_data["email"]
        usuario.is_active = True
        usuario.is_superuser = False

        # user.save()

        usuario.telefone = telefone
        usuario.cidade = cidade
        usuario.save()

        if len(tipo) == 1:
            if '2' in tipo:
                veiculo = Veiculo.objects.create(placa=placa_veiculo, cor=cor_veiculo, modelo=modelo_veiculo, ano=ano_veiculo)
                motorista.usuario = usuario
                motorista.veiculo = veiculo
                motorista.save()
            elif '1' in tipo:
                passageiro.usuario = usuario
                passageiro.save()
        else:
            veiculo = Veiculo.objects.create(placa=placa_veiculo, cor=cor_veiculo, modelo=modelo_veiculo, ano=ano_veiculo)
            motorista.usuario = usuario
            motorista.veiculo = veiculo
            motorista.save()
            passageiro.usuario = usuario
            passageiro.save()

        return usuario

comum/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load comum_extras %}

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Minha Carona</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="{% static 'comum/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'comum/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'comum/css/skin-blue.min.css' %}">
    <style type='text/css'>
    ul{
    list-style-type: none;
    padding: 0;
  }

  </style>
    {% block extra_css %}{% endblock %}
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>MC</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Minha</b>Carona</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">Mensagens</li>
                  <li class="footer"><a href="{% url 'comum:mensagens'%}">Ver todas as mensagens</a></li>
                </ul>
              </li>
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <img src="{% static 'comum/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs">
                    {% if request.user.first_name and request.user.last_name %}
                      {{ request.user.first_name|title }} {{ request.user.last_name|title }}
                    {% elif request.user.first_name %}
                      {{ request.user.first_name|title }}
                    {% else %}
                      {{ request.user.username|title }}
                    {% endif %}
                  </span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <img src="{% static 'comum/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                    <p>
                      {% if request.user.first_name and request.user.last_name %}
                        {{ request.user.first_name|title }} {{ request.user.last_name|title }}
                      {% elif request.user.first_name %}
                        {{ request.user.first_name|title }}
                      {% else %}
                        {{ request.user.username|title }}
                      {% endif %}
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-right">
                      <a href="{% url 'comum:logout' %}" class="btn btn-default btn-flat">Sair</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{% static 'comum/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>
                {% if request.user.first_name and request.user.last_name %}
                  {{ request.user.first_name|title }} {{ request.user.last_name|title }}
                {% elif request.user.first_name %}
                  {{ request.user.first_name|title }}
                {% else %}
                  {{ request.user.username|title }}
                {% endif %}
              </p>
              <!-- Status -->
            </div>
          </div>

          <!-- search form (Optional) -->
          <!-- /.search form -->

          <!-- Sidebar Menu -->
          <ul class="sidebar-menu live-search-list">
            <!-- Optionally, you can add icons to the links -->
            <li class="{% block index %}{% endblock %}"><a href="{% url 'comum:index' %}"><i class="fa fa-link"></i> <span>Início</span></a></li>
            <li class="{% block novo_ponto %}{% endblock %}"><a href="{% url 'comum:novo_ponto' %}"><i class="fa fa-link"></i> <span>Novo Ponto de Interesse</span></a></li>
            <li class="{% block novo_rota %}{% endblock %}"><a href="{% url 'comum:nova_rota' %}"><i class="fa fa-link"></i> <span>Nova Rota de Interesse</span></a></li>
            {% if request.session.tipo == '1' %}
            <li class="{% block novo_pedido_carona %}{% endblock %}"><a href="{% url 'comum:novo_pedido_carona' %}"><i class="fa fa-link"></i> <span>Pedir Carona</span></a></li>
            {% endif %}
            {% if request.session.tipo == '2' %}
            <li class="{% block novo_oferecer_carona %}{% endblock %}"><a href="{% url 'comum:novo_oferecer_carona' %}"><i class="fa fa-link"></i> <span>Oferecer Carona</span></a></li>
            {% endif %}
            <li class="{% block historico %}{% endblock %}"><a href="{% url 'comum:historico' %}"><i class="fa fa-link"></i> <span>Meu Histórico</span></a></li>
          </ul>
          <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        {% block breadcrumb %}{% endblock %}
      {% if messages %}
        <div class='row'>
          <div class='col-md-12'>
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
                {% endfor %}
      </div>
      </div>
    {% endif %}

        {% block content %}{% endblock %}
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <!-- Default to the left -->
        <strong>
          <a href="#">Sistema Minha Carona</a>
        </strong>
      </footer>
      <!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
    </div>
    <!-- ./wrapper -->


    <script src="{% static 'comum/js/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'comum/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'comum/js/app.min.js' %}"></script>
    <script src="{% static 'comum/js/live-search.js' %}"></script>
    

    {% block extra_js %}{% endblock %}
  </body>
</html>

comum/templates/novo_usuario.html
<!DOCTYPE html>
{% load staticfiles %}
{% load comum_extras %}

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Minha Carona</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'comum/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'comum/css/AdminLTE.min.css' %}">
  <style type='text/css'>
    ul{
    list-style-type: none;
    padding: 0;
  }

  .show, .hide {float: left; display: inline-block;}
  .defaut, .hide {margin: 0px; padding: 0px; width: 40px; float: left; text-align: center; }
  .langue {  width: 60px; }
  .defaut {display: inline-block;  }
  .hide {display: none; }

  </style>
</head>

<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>Cadastre-se</b></a>
  </div>
  {% if messages %}
      {% for message in messages %}
      <div class="alert alert-dismissible" role="alert">
          <button style="margin-top: 12px;" type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <h4 style="margin-top: 12px;">{{ message }}</h4>
      </div>
      {% endfor %}
  {% endif %}
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Novo Usuário</p>

    <form action="" method="post">
      {% csrf_token %}

      {{ form.username.errors }}
      {{ form.username.label_tag }}
      <div class="form-group has-feedback">
        {{ form.username|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>

      {{ form.email.label_tag }}
      <label for="id_email">Email:</label>
      <div class="form-group has-feedback">
        {{ form.email|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      {{ form.telefone.label_tag }}
      <div class="form-group has-feedback">
        {{ form.telefone|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-earphone form-control-feedback"></span>
      </div>

      {{ form.cidade.label_tag }}
      <div class="form-group has-feedback">
        {{ form.cidade|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-globe form-control-feedback"></span>
      </div>

      {{ form.password1.errors }}
      {{ form.password1.label_tag }}
      <div class="form-group has-feedback">
        {{ form.password1|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      {{ form.password2.errors }}
      <label for="id_password2">Confirme a senha:</label>
      <div class="form-group has-feedback">
        {{ form.password2|add_css_class:'form-control' }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

      {{ form.tipo.errors }}
      <div class="form-group">
        {{ form.tipo }}
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

      <div class="hide veiculo">
        <label>Veículo</label>
        <br>
        {{ form.cnh.label_tag }}
        <div class="form-group has-feedback">
          {{ form.cnh|add_css_class:'form-control' }}
          <span class="glyphicon glyphicon-credit-card form-control-feedback"></span>
        </div>
        <label for="id_modelo_veiculo">Informe o modelo do seu veículo:</label>
        <div class="form-group has-feedback">
          {{ form.modelo_veiculo|add_css_class:'form-control' }}
          <span class="glyphicon glyphicon-file form-control-feedback"></span>
        </div>

        <label for="id_placa_veiculo">Informe a placa do seu veículo:</label>
        <div class="form-group has-feedback">
          {{ form.placa_veiculo|add_css_class:'form-control' }}
          <span class="glyphicon glyphicon-file form-control-feedback"></span>
        </div>

        <label for="id_cor_veiculo">Informe a cor do seu veículo:</label>
        <div class="form-group has-feedback">
          {{ form.cor_veiculo|add_css_class:'form-control' }}
          <span class="glyphicon glyphicon-file form-control-feedback"></span>
        </div>

        <label for="id_ano_veiculo">Informe o ano do seu veículo:</label>
        <div class="form-group has-feedback">
          {{ form.ano_veiculo|add_css_class:'form-control' }}
          <span class="glyphicon glyphicon-file form-control-feedback"></span>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Criar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'comum/js/jquery-2.2.3.min.js' %}"></script>
<script>
  $( "#id_tipo_1" ).change(function() {
    if($(this).is(":checked")){
      $( ".veiculo" ).removeClass('hide');
    }else{
      $( ".veiculo" ).addClass('hide');
    }
  });
  $(document).ready(function(){
    if($("#id_tipo_1").is(":checked")){
      $( ".veiculo" ).removeClass('hide');
    }else{
      $( ".veiculo" ).addClass('hide');
    }
  });
</script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'comum/js/bootstrap.min.js' %}"></script>
</body>
</html>